[package]
name = "uv_sphere"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rose-core = { path = "../../lib/rose-core" }
rose-platform = { path = "../../lib/rose-platform", features = ["ui"] }
rose-ui = { path = "../../lib/rose-ui" }
violette = { path = "../../lib/violette" }

bytemuck.workspace = true
egui.workspace = true
eyre.workspace = true
glam.workspace = true
tracing.workspace = true
