[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.7"
color-eyre = "0.6.2"
dashmap = "5.4.0"
egui_dock = "0.3.1"
egui-gizmo = "0.9.0"
rayon = "1.6.1"
rfd = "0.11.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
serde_yaml = "0.9.17"
toml = "0.7.2"
toml_edit = "0.19.4"
typetag = "0.2.5"

input = { path = "../../lib/input" }
rose-core = { path = "../../lib/rose-core", features = ["serialize"] }
rose-ecs = { path = "../../lib/rose-ecs", features = ["ui"] }
rose-platform = { path = "../../lib/rose-platform", features = ["ui"] }
rose-renderer = { path = "../../lib/rose-renderer", features = ["debug-ui"] }
violette = { path = "../../lib/violette" }

egui.workspace = true
eyre.workspace = true
glam = { workspace = true, features = ["serde"] }
tracing.workspace = true
