[package]
name = "many-spheres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rose-core = { path = "../../lib/rose-core" }
rose-platform = { path = "../../lib/rose-platform", features = ["ui"] }
rose-ui = { path = "../../lib/rose-ui" }
rose-renderer = { path = "../../lib/rose-renderer" }
violette = { path = "../../lib/violette" }

bytemuck.workspace = true
egui.workspace = true
eyre.workspace = true
glam.workspace = true
tracing.workspace = true
rand = "0.8.5"

